export const SLIDER_IMAGES_LOADING = 'SLIDER_IMAGES_LOADING';
export const SLIDER_IMAGES_FAILED = 'SLIDER_IMAGES_FAILED';
export const ADD_SLIDER_IMAGES = 'ADD_SLIDER_IMAGES';
export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const DESTINATIONS_FAILED = 'DESTINATIONS_FAILED';
export const ADD_DESTINATIONS = 'ADD_DESTINATIONS';
